# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/181ps2uLQL07zi8KbyWqA4Mf5PPJIiO0B
"""

from googlesearch import search 

term = 'python'

for i in search(term, num_results=20, lang='es'):
  print(i)